### ISSUE TITLE
Bedrock TODO List

### ISSUE THREAD

**Issue by 95CivicSi** [RevivalPMMP/PureEntitiesX#236]
This is a revised TODO list based on #61 but updated for Bedrock Edition and modified to eliminate general TODO items that need specifics.  Items will be added and updated as necessary.  See this for more information:
https://github.com/RevivalPMMP/PureEntitiesX/wiki/The-TODO-List

## **General AI**
- [ ] Fix Entity Movement code
  - [ ] Entities should spend most of their time idling unless provoked
  - [ ] Walking movements should be in short intervals
  - [ ] Moving to new locations should not always be at full speed
  - [ ] Walking animations should not use full range of leg motion for every move.
  - [ ] Entities should make movement decisions that consider fall damage.
<br>

- [ ] Fix 'JumpingEntity' so mobs actually hop.
- [ ] Fix 'FlyingEntity' so mobs actually fly.
- [x] Fix XP Orbs
- [x] Re-Fix XP Orbs and associated function to work with new API.
- [x] Update NBT methods to use new API.
- [x] Fix Entities Standing/Spawing on top of other mobs.
- [ ] Fix EndermanLookingTask
  - [x] Change BlockIteration to Use New VoxelRayTrace Class
- [ ] Finish implementing 'Traits'
  - [ ] Breedable
  - [ ] Can Panic
  - [ ] Feedable
  - [ ] Rideable
  - [ ] Shearable
  - [ ] Tameable
    - [ ] When commanded to sit, tamed mobs should not teleport to owner (even when owner enters the world).
- [ ] Add Inventory options to Horse types.

## **Entity Specific**
**Passive Mobs**

- [ ] Bat
  - [ ] Implement
- [ ] Chicken
  - [x] Implement
- [ ] Cow
  - [x] Implement
- [ ] Donkey
  - [x] Implement
- [ ] Horse
  - [x] Implement
- [ ] Llama
  - [x] Implement
- [ ] Mooshroom
  - [x] Implement
  - [ ] Add Shearing Trait
  - [ ] Add Milking Trait 
- [ ] Mule
  - [x] Implement
- [ ] Ocelot
  - [x] Implement
  - [ ] Add Begging Mode
  - [x] Make Failed Tame Attempts Trigger Breeding Mode
- [ ] Parrots
  - [x] Implement
  - [ ] Make Parrots respond to Sit commands.
  - [ ] Make Parrots Dance when near active jukeboxes.
  - [ ] Make Parrots die and emit poison particles when fed a cookie
- [ ] Pig
  - [x] Implement
- [ ] Rabbit
  - [x] Implement
- [ ] Sheep
  - [x] Implement
- [ ] Skeleton Horse
  - [x] Implement
- [ ] Squid
  - [ ] Implement
- [ ] Villager
  - [x] Implement

**Hostile Mobs**
- [ ] Blaze
  - [x] Implement
  - [ ] Fix Fireball Calculations
- [ ] Cave Spiders
  - [x] Implement
- [ ] Creepers 
  - [x] Implement
  - [ ] Allow creepers to be exploded by flint and steel
  - [ ] Creepers should flash when internal fuse is 'lit'
<br>

- [ ] Enderman
  - [x] Implement
- [ ] Endermite
  - [x] Implement
- [ ] Evoker
  - [x] Implement
- [ ] Ghast
  - [x] Implement
- [ ] Guardian
  - [ ] Implement
- [ ] Husk
  - [x] Implement
  - [ ] Babies
- [ ] IronGolem
  - [x] Implement
- [ ] Magma Cube
  - [x] Implement
- [ ] Pig Zombie
  - [x] Implement
- [ ] Polar Bear
  - [x] Implement
- [ ] Shulker
  - [x] Implement
- [ ] Silverfish
  - [x] Implement
- [ ] Skeleton
  - [x] Implement
  - [ ] Add Bow in Hand
- [ ] Slime
  - [x] Implement
- [ ] Snow Golem
  - [x] Implement
- [ ] Spider
  - [x] Implement
- [ ] Stray
  - [ ] Implement
- [ ] Vex
  - [x] Implement
- [ ] Vindicator
  - [x] Implement
- [ ] Witch
  - [x] Implement
  - [ ] Modify Drop Method
  - [ ] Enable AutoSpawn
  - [ ] Update Attack Methods
- [ ] Wither Skeleton
  - [x] Implement
  - [ ] Add Stone Sword in Hand
- [ ] Wolf
  - [x] Implement
  - [x] Collar color not persistent on server restarts.
- [ ] Zombie
  - [x] Implement
  - [ ] Babies
- [ ] Zombie Pigman
  - [x] Implement
  - [ ] Babies
  - [ ] Golden Sword
  - [ ] Behavior Specifics
- [ ] Zombie Villager
  - [x] Implement
  - [ ] Babies
  - [ ] Curing

**Bosses**

- [ ] Elder Guardian
  - [ ] Implement
- [ ] Ender Dragon
  - [ ] Implement
- [ ] Wither
  - [ ] Implement

**Comment by NycuRO** [comment]
@95CivicSi Seriously? You closed my PR, a good TODO for this shit with 5 lines? -_-

**Comment by 95CivicSi** [comment]
Yes, seriously.  5 lines was a primer.  I did mention that it would be updated.   Like it is now.  (Still lots more to add).

**Comment by jasonwynn10** [comment]
should start using new API
https://github.com/pmmp/PocketMine-MP/commit/50be26958a58d66ae022b3cd0f3193ceafff8d94#diff-9649873f1670ddd60984257dd0380943R299

**Comment by Infernus101** [comment]
Implement bosses

**Comment by jasonwynn10** [comment]
dktapps is about to break more API... prepare to fix XP

**Comment by Infernus101** [comment]
:( Breaking API should be illegal, so much work ❌

**Comment by jasonwynn10** [comment]
https://github.com/pmmp/PocketMine-MP/commit/3c2b9279ab6c0ce94a74f623b4e0323271ca38b0

**Comment by Infernus101** [comment]
already added that lel

**Comment by Infernus101** [comment]
lol @jasonwynn10 triggered

**Comment by 95CivicSi** [comment]
I can't even begin to explain how aggravating that is.

**Comment by 95CivicSi** [comment]
So, I did some initial testing on the Working XP branch.  Our code still works as expected.  As long as changes aren't made to setXpProgress() and setXpLevel() (which it doesn't look like will change), we'll be OK.  For now I'm going to work on more important items like movement fixes and implementing other creatures.

**Comment by jasonwynn10** [comment]
This is handy
https://github.com/pmmp/PocketMine-MP/commit/ea16ea4dcdae7dd3c092558bd29474cda2690e49#diff-43a4bad7f0d5a94c78f006dae48b2370R1588

**Comment by jasonwynn10** [comment]
This will be needed for memory leak fixes
https://github.com/pmmp/PocketMine-MP/pull/1490

**Comment by 95CivicSi** [comment]
Agreed.  Both of those will be useful.  The flagForDespawn() will probably solve issues related to getBlock on null.

**Comment by jasonwynn10** [comment]
This new API is useful for endermen
https://github.com/pmmp/PocketMine-MP/commit/8daa8deae99c88a649d09b1b640796ae24260df6

**Comment by Adam1609** [comment]
It is January and you should tick the Todo list now XD

**Comment by jasonwynn10** [comment]
https://twitter.com/_tomcc/status/957115024455053312 :D

**Comment by 95CivicSi** [comment]
Not sure how much that's going to help on our end of things @jasonwynn10.  We'll see as things move along.

**Comment by jasonwynn10** [comment]
If all is well with no client lag, then it doesn't require as many optimizations from us during development

**Comment by 95CivicSi** [comment]
Eh.  I think the biggest lag issue is general handling of entities.  Try dropping a few hundred pork chops and watch the server bog down.

Updates to the list as of today:

- Fixed Wolf Collar Color Persistence on Server Restarts
- Implemented all Mobs (even if they don't have completely unique methods)
- Updated Tameable
- Updated NBT Methods
- Changed BlockIteration to use VoxelRayTrace.  This will hopefully help the EndermanLookingTask and Interaction Tasks.

**Comment by NycuRO** [comment]
This TODO don't have all of my todo's.
Add all of them.
