### ISSUE TITLE
Bug TODO List

### ISSUE THREAD

**Issue by NycuRO** [RevivalPMMP/PureEntitiesX#61]
- [x] 1. Wolves cannot be tamed #215
- [x] 2. Wolves eyes don't change color when aggravated
- [ ] 3. General AI glitches
- [ ] 4. Attacked Animals don't run from players
- [ ] 5. Ocelots don't run from players
- [x] 6. Mooshrooms cannot be sheared #112 
- [x] 7. The shear button is hidden on sheep and mooshrooms #112 
- [ ] 8. Bats don't fly to move
- [ ] 9. Rabbits don't hop to move
- [x] 10. Horses, Donkeys, etc.. don't have any UI
- [x] 11. Skeleton Horses don't spawn
- [x] 12. Creeper bug: (probably due to non-pmmp server software)
`[18:56:19] [Server thread/CRITICAL]: Could not tick level "world3": Argument 3 passed to pocketmine\event\entity\ExplosionPrimeEvent::__construct() must be of the type boolean, none given, called in phar:///root/skyblock/plugins/phar_PureEntitiesX-master_I4CmvWjM8PCXtau.phar/src/revivalpmmp/pureentities/entity/monster/walking/Creeper.php on line 62`
- [x] 13. Tameable animals don't sit
- [ ] 14. Enderman don't attack when looked at
- [ ] 15. Slimes don't differ in size
- [x] 16. The spiders don't climb walls
- [ ] 17. Squids are invisible in water.
- [x] 18. Cave Spider doesn't poison it's attacker
- [x] 20. Other error:
`[19:02:21] [Server thread/CRITICAL]: Could not tick level "world3": Undefined class constant 'WITHER_SKELETON_SKULL'`
- [x] 21. Guardians don't spawn
- [ ] 22. Magma Cube & Slime not leat (I can't translate this better -Jason)
- [x] 23. Magma Cubes drop gunpowder
- [x] 24. Nether mobs are missing proper AI
- [x] 25. Iron Golems don't spawn
- [x] 26. Other error: (probably due to non-pmmp server software)
`[19:05:36] [Server thread/CRITICAL]: Could not tick level "world3": Argument 3 passed to pocketmine\event\entity\ExplosionPrimeEvent::__construct() must be of the type boolean, none given, called in phar:///root/skyblock/plugins/phar_PureEntitiesX-master_I4CmvWjM8PCXtau.phar/src/revivalpmmp/pureentities/entity/projectile/FireBall.php on line 82`
- [x] 27. Snow Golems cannot be sheared #112 
- [x] 28. Ocelots need to have all skins available after being tamed
- [ ] 29. Creepers don't run from ocelots
- [ ] 30. jockeys ride on the same type of mob as themselves
- [x] 31. mobs don't drop XP orbs
- [ ] 32. Baby mobs
- [x] 33. Colored sheep don't spawn 
- [x] 34. Drop colored wool ( sheep colored )
- [ ] 35. Witches don't hold potions
- [x] 37. Chickens don't lay eggs
- [ ] 38. Pigs don't follow direction of the carrot on a stick
- [ ] 39. Saddle support on Horse
- [x] 40. Saddle support on Pig.
- [x] 41. Mating particles don't immediately dissappear
- [ ] 42. Horses spawn in all biomes
- [ ] 43. Jumps are buggy
- [ ] 44. Entities do not jump over blocks
- [x] 45. Make mobs smarter
- [ ] 46. Entities jump too high on slabs
- [ ] 47. Animals cannot use ladders
- [x] 48. Entitys and Lava particles despawn from Spawners on unload chunks and task despawning
- [x] 49. Incorrect Spawner Particles
- [ ] 50. Mob Spawners have leads
- [x] 51. If you killed creeper, he explode.
- [x] 52. Wolf not teleport near player
- [x] 53. Animals and zombies can not attack at all
# NO MORE

**Comment by Rover656** [comment]
Pretty much all of these are known

**Comment by jasonwynn10** [comment]
How does the speed change after being hit?

**Comment by NycuRO** [comment]
@Rover656 I'm very informated in this chapter. 

This bugs is because PureEntities have this issues because have moving by MobAI.

Official speed and ~ all mobs have speed from task ( in pc ).

**Comment by NycuRO** [comment]
@jasonwynn10 If you attack animals , change speed for 5 sec. Wait for creating video.

**Comment by Magicode1** [comment]
Nether Mobs Should Have AI. A few errors might be caused if you are using the new MCPE 1.0 branch of PMMP

**Comment by NycuRO** [comment]
@Magicode1 I'm not using 1.0 branch.

**Comment by NycuRO** [comment]
Is master.

**Comment by caspervanneck** [comment]
lol

**Comment by caspervanneck** [comment]
it has no eror the 1.0.0 branch

**Comment by caspervanneck** [comment]
zo what

**Comment by Sandertv** [comment]
This is all known and most reported. Almost all are things that have not been added yet.

**Comment by Magicode1** [comment]
Ok. The "Could not Tick Level" Has to do with your computer. Whenever the mobs cause your server to freeze for a second (Aka Normal Lag), since it is PureEntities that caused it (It would be Pocketmine itself, but it doesn't have mobs, our plugin is what makes the mobs), Pocketmine reports it to the console.

**Comment by caspervanneck** [comment]
and @NycuRO its in wip so

**Comment by Sandertv** [comment]
Oh and sheep do show the shear buttons btw.

**Comment by NycuRO** [comment]
@Sandertv In creative mode not.

**Comment by Sandertv** [comment]
It should if you have shears in your hands...

**Comment by Sandertv** [comment]
Oh wait nvm you're right.

**Comment by Sandertv** [comment]
But why would you want to shear sheep in creative mode anyways?

**Comment by NycuRO** [comment]
And video for change speed here: https://youtu.be/XxEMSJKSCZg

**Comment by Sandertv** [comment]
And for the creeper bug you must be using Genisys or something. It shouldn't occur on PMMP.

**Comment by NycuRO** [comment]
@Sandertv I'm using PMMP

**Comment by caspervanneck** [comment]
sorry if i say genisys  is bad!

**Comment by caspervanneck** [comment]
its junk

**Comment by Sandertv** [comment]
For the creeper error, try now.

**Comment by jasonwynn10** [comment]
btw I went through and made clearer english out of what was typed

**Comment by NycuRO** [comment]
@Sandertv Work explosion. But not break blocks and not work particles and not drop items.

**Comment by Sandertv** [comment]
I'll add block breaking later once config gets added, so people can configure if they damage terrain or not. For now I'm leaving it like this.

**Comment by Sandertv** [comment]
And the squid issue is in fact a PocketMine problem. PocketMine has squids implemented sort of.

**Comment by NycuRO** [comment]
28. When you creeper seeks to rumble, it is no longer salt blocks.

**Comment by jasonwynn10** [comment]
what keeps being translated into salt??

**Comment by NycuRO** [comment]
@jasonwynn10 Jump*

**Comment by jasonwynn10** [comment]
@Sandertv can't we just extend our squid class off of pocketmine's?

**Comment by jasonwynn10** [comment]
@NycuRO thank you!

**Comment by NycuRO** [comment]
Welcome. @jasonwynn10

**Comment by NycuRO** [comment]
I continue to search bugs and add in this issue. I'm added "EDIT" in this issue.

I add all my issues in this.

**Comment by jasonwynn10** [comment]
ima put check boxes by each issue to be checked off when it's fixed

**Comment by Magicode1** [comment]
About the Cave spider attacking witches. Witches throw potions, and when they hit mobs, the mobs attack it.

**Comment by NycuRO** [comment]
@Magicode1 Witch not have in hand potion.

EDIT: add 37

**Comment by Sandertv** [comment]
Not yet implemented either.

**Comment by NycuRO** [comment]
I know. And features added in issue . Is more easier for watch bugs and not implemented features

**Comment by kniffo80** [comment]
I would call this a more or less a feature list ;) Hi @NycuRO moved to PHP based Pocketmine? ;)

**Comment by NycuRO** [comment]
@kniffo80 I don't understand what you say..

**Comment by caspervanneck** [comment]
lol

**Comment by kniffo80** [comment]
Nevermind @NycuRO we had contact within Nukkit and another mob plugin ;)

**Comment by Magicode1** [comment]
Some of the mobs (Guardian, Iron Golem) Won't spawn until structures come out.

**Comment by jasonwynn10** [comment]
we can still allow the golem to spawn with its block formation

**Comment by kniffo80** [comment]
@jasonwynn10  The 1.0.0-bug-fixes auto spawns golems, if you configure so ;) - was my latest PR

**Comment by Magicode1** [comment]
Yeah, I checked all of the redundant ones, like skeleton horses. They aren't supposed to spawn naturally. We can add them later, but we aren't focusing on special mobs right now. We could possibly make another plugin for special mobs, we just need to get a team together to work on it. If you're interested, contact me over the gitter chat.

**Comment by NycuRO** [comment]
@Magicode1 You can add in this plugin? Because is MobAI feature..

**Comment by Magicode1** [comment]
Depends. I need to see what everyone wants to do.

**Comment by Magicode1** [comment]
https://goo.gl/H2AaiX

Please vote there.

**Comment by jasonwynn10** [comment]
@Magicode1 what were the vote results?

**Comment by NycuRO** [comment]
Updated. @Magicode1 @kniffo80 @Sandertv

**Comment by jasonwynn10** [comment]
@NycuRO I removed some of those things because this isn't PC minecraft. We are trying to match up the AI to Vanilla Pocket Edition Minecraft.

**Comment by NycuRO** [comment]
@jasonwynn10 Uses same code ,but in C++.

**Comment by jasonwynn10** [comment]
It doesn't work that way 100% though, so it is better for us to attempt to use PE Minecraft as much as possible rather than PC

**Comment by NycuRO** [comment]
@jasonwynn10 Decompile MCPE and watch code ;) It's same but in c++ with minors modification for MCPE.

And Support for Entity Items like Boats and other? :)

**Comment by NycuRO** [comment]
Added 38. Pig features.

**Comment by axs-gentoo** [comment]
I noticed in the world i've got that pigs, cows, pretty much everything likes to climb trees (the terrain is hilly and so there are lots of places where players can regularly do a one-block jump and be walking on a tree).  Is this something the MobAI should be adjusted for?

**Comment by archie426** [comment]
@axs-gentoo Probably irrelevant, what PMMP version are you using, are you using a spoon/fork?

**Comment by axs-gentoo** [comment]
PMMP, git master as of Jan.27 (API 3.0.0-ALPHA3) , git checkout of PureEntitiesX that matches (and whatever CI DevTools build I could find that did API3.0.0-ALPHA3).  

It doesn't seem like a bug but rather a possible new feature -- the tree "climbing" is a valid movement so long as the MobAI isn't set to avoid blocks of type leaves (or whatever it'd be called).

**Comment by Sandertv** [comment]
As far as I know nobody fixed the wall climbing from entities yet. The AI isn't exactly perfect yet.

**Comment by LordJoshie** [comment]
Whats the most amount of plugins you're aware of on a public server ? 

My server is world rank #25, pretty modest, got a decent little community... around 70 plugins. 

I'd like to take part in testing this on a fork of pmmp using Genisys/PMMP code. 

Some of you may already know of Tesseract... 

I'd love to feature this on my server, and can test any platform you'd like. 

I prefer Tesseract, but I can compile pmmp and run this plugin on that if you'd like for some of my feedback.

**Comment by AppleDevelops** [comment]
Yo know, you could open an issue on the Tesseract GitHub, and I'd add support no need to spam it here

**Comment by LordJoshie** [comment]
Hey Applqpak ! I didnt know you checked on this xD

And okay, shall do my good sir !

I just tend to request that a plugin be compatible with a platform, opposed
to the platform being compatible with plugin.

Either or works fine for me, the combination of Tess & Revival Entities =
an amazing vanilla server :D

**Comment by jasonwynn10** [comment]
@LordJoshie I think you have the wrong person... lol @AppleDevelops is not appleqpak

**Comment by LordJoshie** [comment]
Then I do.

Thought it was...

**Comment by NycuRO** [comment]
My issue is very best xD ,not closed xD

**Comment by NycuRO** [comment]
Added 39 and 40.

**Comment by jasonwynn10** [comment]
@NycuRO This list is long enough. Please leave anything found to be new for new issues.

**Comment by NycuRO** [comment]
@jasonwynn10 Why? :D

**Comment by jasonwynn10** [comment]
Multiple issues are easier to manage rather than having one that contains everything. We can also label them by priority if there are multiple

**Comment by NycuRO** [comment]
Added 41,42. And @jasonwynn10 Is more easy in one issue. Fix issue at a time.

**Comment by NycuRO** [comment]
Added 43.

**Comment by kniffo80** [comment]
@NycuRO can you describe #41 eventually a little bit more in detail? I don't understand correctly.

**Comment by LordJoshie** [comment]
where are these latest changes being applied to ? 

Not in the main branch ? ...

**Comment by kniffo80** [comment]
At the moment latest is master yes. Currently working in branch "kniffo80"

**Comment by Sandertv** [comment]
@kniffo80 Basically when feeding an animal, it keeps showing these heart particles above the animal that has been fed every second or so, which makes it possible to see which animal is still 'seeking' a partner.

**Comment by kniffo80** [comment]
Ahhhh now i understand. But this is what wiki says: http://minecraft.gamepedia.com/Breeding

This here: **Animals that are in love mode emit heart particles constantly.**

**Comment by NycuRO** [comment]
@kniffo80 test on singleplayer.

**Comment by kniffo80** [comment]
What do the others say? I can remove that of course. But it's the way it's meant to be ... or not?!

**Comment by NycuRO** [comment]
@kniffo80 test on singleplayer breeding.

**Comment by NycuRO** [comment]
Update 43, added 44.

**Comment by kniffo80** [comment]
@NycuRO regarding the love mode emitting thing - i will make it configurable

**Comment by NycuRO** [comment]
@kniffo80 Ok

**Comment by NycuRO** [comment]
Added 46, 47, 48 , 49, 50, 51.

**Comment by jasonwynn10** [comment]
If you want the list to be worked on, stop adding to it.

**Comment by NycuRO** [comment]
Added 52

**Comment by NycuRO** [comment]
Added 53. @kniffo80

**Comment by kniffo80** [comment]
53: if $player->getName() equals "NycuRO" then entity->boom()

52: no comment

xx: why are you tagging me every time? As you may read - I am already assigned to this. So each and every thing added / removed / replaced I will be notified about

**Comment by NycuRO** [comment]
Oh, sorry.

**Comment by kniffo80** [comment]
@NycuRO please try latest https://github.com/RevivalPMMP/PureEntitiesX/tree/kniffo80 for number 53 - i checked it now multiple times. For me, creepers don't explode anymore when killed. And you have to use latest master of PMMP as Tesseract has old spawning with chunk - i adapted the plugin for latest PMMP master.

**Comment by kniffo80** [comment]
@NycuRO i investigated on number 52 - again it's tesseract defining one more constructor variable. In PMMP it's not like it's in tesseract. So please use PMMP if possible.

**Comment by jasonwynn10** [comment]
We <i>did</i> say that we wouldn't give official support for anything but pmmp

**Comment by LordJoshie** [comment]
pmmp isnt as progressed as some other utincels of pmmp.

perhaps try to be as versatile as possible.

is it actually thaaaaat much more difficult to add compatibility with a
type of software that is very near the same ?

**Comment by Sandertv** [comment]
You don't get how annoying it is to make a plugin work with two softwares that have different API until you do it yourself. We don't want to encourage people using 'spoons' from PMMP either.

**Comment by kniffo80** [comment]
@LordJoshie yeah, we try. But sometimes, the functions are not compatible. Then, it's not possible to maintain, even when they're nearly the same. E.g. ExplosionPrimeEvent constructor. Not possible to use Tesseract and PMMP. Just an example.

**Comment by LordJoshie** [comment]
Fair. I feel you guys...trust me. you don't know the struggle I face
setting up and maintaining my server when I have no clue what I'm doing...
I just know trial and error and eventually I get results close to what I
want and work with it.

been doing alright so far xD

Not sure the age group here, but I feel old... I'm 26, and a noob when it
comes to this stuff. I just try to stay in the loop so my server and people
don't deminish.

Perhaps people wouldn't resort to utencils of pmmp if pmmp found a way to
code in what other utencils have working already.

But back that struggle of making things work.... I gotcha.

just when I think I'll have a stable streak for my server, Mojang drops an
update, the servers change protocols, and I have to update...

the worst was unpacking 70+ plugins from phar to change the API... fun
wowie.

and I do most of this off my phone.
servers been up a year, and a bit, and I just got my PC a month or so ago.

xD
ya'll are doing damn good. so I'm sure it's whatever... maybe Apple
develops will add support for this to his server software ? ;) Ayeeeee.

I'm sure if I ask hella nicely, he'd consider. :P

**Comment by kniffo80** [comment]
@NycuRO the ExplosionPrimeEvent thing should be fixed on kniffo80 branch - please check!

**Comment by NycuRO** [comment]
Fixed 53, added 54 and 55.

**Comment by kniffo80** [comment]
For 54 I know. For 55 - it moves instantly to your location when it gets x blocks away. Cannot remember now. Will set the value higher. There's something about when wolf teleports in wiki. I think I used that values. But I will check.

**Comment by kniffo80** [comment]
@LordJoshie check latest master together with Tesseract... should work!

**Comment by archie426** [comment]
@LordJoshie If that is how you understand spoons then maybe you should just look around a bit. Perhaps take a look at some of the spoons code, and compare it to PMMP

**Comment by NycuRO** [comment]
53 not fixed on Tesseract.

**Comment by NycuRO** [comment]
Added 56.

**Comment by kniffo80** [comment]
Man your descriptions suck - sorry to say that.

**Comment by NycuRO** [comment]
@kniffo80 Edit if you don't like

**Comment by NycuRO** [comment]
Added 57.

**Comment by kniffo80** [comment]
@NycuRO edit if you don't like? Whats wrong with you? When i don't understand what you write here I simply cannot edit and correct descriptions right?

**Comment by NycuRO** [comment]
@kniffo80 Ok, ready, updated. 56.

**Comment by kniffo80** [comment]
Now i got it ...

**Comment by kniffo80** [comment]
**52: Wolf not teleport near player** - checked this - they teleport when not sitting!
**53: Animals and zombies can not attack at all** - spawned a zombie at night and he's attacking me!

Can anyone confirm that this works fine? At least tested with PMMP.

**Comment by NycuRO** [comment]
@kniffo80 If have distance < 2 ,not attack on 53 issue.

**Comment by kniffo80** [comment]
So you mean when distance to the player is lower than 2 blocks it doesn't attack?

**Comment by kniffo80** [comment]
Or you mean when distance < 2 they SHOULD NOT attack?

**Comment by NycuRO** [comment]
Yes.

**Comment by NycuRO** [comment]
Same variants.

**Comment by kniffo80** [comment]
Okay let me summarize:
- when distance > 2 to the player / entity - they should attack
- when distance < 2 they should not attack

Is that correct?

**Comment by kniffo80** [comment]
When this is meant - i just run into an entity and they won't attack. Do you think this is really the case?

**Comment by NycuRO** [comment]
Yes, on Tesseract. Please Test on my server: nycuro.ddns.net

**Comment by kniffo80** [comment]
This makes absolutely no sense to me. This is a strange behavior to be implemented. What does the team say?

**Comment by NycuRO** [comment]
@kniffo80 Enter on my server: nycuro.ddns.net, to section "Factions". It's latest Tesseract Version and latest PureEntitiesX AND TEST ATTACK.

**Comment by kniffo80** [comment]
Try it out on vanilla PMMP Server! I read Tesseract and Plugins ... Please before opening a bug try it out on vanilla PMMP with this as only plugin.

Again - I've not that much time. Because this plugin is not my main job ... i'm doing it only besides of the rest of my life.

**Comment by jasonwynn10** [comment]
I am going to test it later today

**Comment by Magicode1** [comment]
For **47. Animals cannot use ladders** 

Are they even supposed to be able to?

**Comment by jasonwynn10** [comment]
It's in vanilla...

**Comment by jasonwynn10** [comment]
Passing to https://github.com/poggit-orphanage/PureEntitiesX

**Comment by 95CivicSi** [comment]
A nice TODO.  
Updates to Wolf that fix sitting and collar in https://github.com/RevivalPMMP/PureEntitiesX/commit/f365102ededeecd0a5aae7804c6c27ff293a2a5d

**Comment by 95CivicSi** [comment]
@jasonwynn10 What is this in reference too?

"Magma Cube & Slime not leat (I can't translate this better -Jason)"

**Comment by jasonwynn10** [comment]
I couldn't translate what was posted any better, and I have no idea what that means

**Comment by 95CivicSi** [comment]
Do you know where the original post is?

**Comment by jasonwynn10** [comment]
The original post doesn't exist anymore. I edited the first post for legibility, removing what was there originally

**Comment by 95CivicSi** [comment]
Ok.  Thank you.

**Comment by 95CivicSi** [comment]
Closing issue and moving to TODO list in #236.
